import {
    OptScaCatpcaBootstrapType, OptScaCatpcaCategoryPlotsType,
    OptScaCatpcaDefineRangeScaleType,
    OptScaCatpcaDefineScaleType,
    OptScaCatpcaDiscretizeType, OptScaCatpcaLoadingPlotsType,
    OptScaCatpcaMainType,
    OptScaCatpcaMissingType, OptScaCatpcaObjectPlotsType,
    OptScaCatpcaOptionsType,
    OptScaCatpcaOutputType,
    OptScaCatpcaSaveType,
    OptScaCatpcaType
} from "@/models/dimension-reduction/optimal-scaling/catpca/optimal-scaling-captca";

export const OptScaCatpcaMainDefault: OptScaCatpcaMainType = {
    SrcVar: null,
    AnalysisVars: null,
    SuppleVars: null,
    LabelingVars: null,
    Dimensions: null,
};

export const OptScaCatpcaDefineRangeScaleDefault: OptScaCatpcaDefineRangeScaleType = {
    Weight: null,
    SplineOrdinal: false,
    SplineNominal: false,
    MultipleNominal: false,
    Ordinal: false,
    Nominal: false,
    Numeric: false,
    Degree: null,
    InteriorKnots: null,
};

export const OptScaCatpcaDefineScaleDefault: OptScaCatpcaDefineScaleType = {
    SplineOrdinal: false,
    SplineNominal: false,
    MultipleNominal: false,
    Ordinal: false,
    Nominal: false,
    Numeric: false,
    Degree: null,
    InteriorKnots: null,
};

export const OptScaCatpcaDiscretizeDefault: OptScaCatpcaDiscretizeType = {
    VariablesList: null,
    Method: null,
    NumberOfCategories: false,
    NumberOfCategoriesValue: null,
    DistributionNormal: false,
    DistributionUniform: false,
    EqualIntervals: false,
    EqualIntervalsValue: null,
};

export const OptScaCatpcaMissingDefault: OptScaCatpcaMissingType = {
    CurrentTargetList: null,
    AnalysisVariables: null,
    SupplementaryVariables: null,
    MissingValuesExclude: false,
    ExcludeMode: false,
    ExcludeExtraCat: false,
    ExcludeRandomCat: false,
    MissingValuesImpute: false,
    ImputeMode: false,
    ImputeExtraCat: false,
    ImputeRandomCat: false,
    ExcludeObjects: false,
};

export const OptScaCatpcaOptionsDefault: OptScaCatpcaOptionsType = {
    RangeOfCases: false,
    First: null,
    Last: null,
    SingleCase: false,
    SingleCaseValue: null,
    NormalizationMethod: null,
    NormCustomValue: null,
    Convergence: null,
    MaximumIterations: null,
    VariableLabels: false,
    LimitForLabel: null,
    VariableNames: false,
    PlotDimDisplayAll: false,
    PlotDimRestrict: false,
    PlotDimLoDim: null,
    PlotDimHiDim: null,
    ConfigurationMethod: null,
    ConfigFile: null,
    None: false,
    Varimax: false,
    Oblimin: false,
    Delta: null,
    Quartimax: false,
    Equimax: false,
    Promax: false,
    Kappa: null,
    Kaiser: false,
};

export const OptScaCatpcaOutputDefault: OptScaCatpcaOutputType = {
    QuantifiedVars: null,
    LabelingVars: null,
    CatQuantifications: null,
    DescStats: null,
    ObjScoresIncludeCat: null,
    ObjScoresLabelBy: null,
    ObjectScores: false,
    CorreOriginalVars: false,
    ComponentLoadings: false,
    CorreTransVars: false,
    SortBySize: false,
    IterationHistory: false,
    Variance: false,
};

export const OptScaCatpcaSaveDefault: OptScaCatpcaSaveType = {
    Discretized: false,
    DiscNewdata: false,
    DiscDataset: null,
    DiscWriteNewdata: false,
    DiscretizedFile: null,
    SaveTrans: false,
    Trans: false,
    TransNewdata: false,
    TransDataset: null,
    TransWriteNewdata: false,
    TransformedFile: null,
    SaveObjScores: false,
    ObjScores: false,
    ObjNewdata: false,
    ObjDataset: null,
    ObjWriteNewdata: false,
    ObjScoresFile: null,
    SaveApprox: false,
    Approx: false,
    ApproxNewdata: false,
    ApproxDataset: null,
    ApproxWriteNewdata: false,
    ApproximationsFile: null,
    BTLoading: false,
    BTObject: false,
    BTCategories: false,
    BTEllipseCoord: false,
    BTNewDataset: false,
    BTDatasetName: null,
    BTWriteDataFile: false,
    BTFileText: null,
    All: false,
    First: false,
    MultiNomDim: null,
};

export const OptScaCatpcaBootstrapDefault: OptScaCatpcaBootstrapType = {
    PerformBT: false,
    Balanced: false,
    Unbalanced: false,
    NumberSamples: null,
    ConfLevel: null,
    Procrustes: false,
    Reflection: false,
    ThresholdLoading: null,
    ThresholdObject: null,
    ThresholdCategory: null,
    OperatorLoading: null,
    OperatorObject: null,
    OperatorCategory: null,
    ValueLoading: null,
    ValueObject: null,
    ValueCategory: null,
    NumberPoints: null,
};

export const OptScaCatpcaObjectPlotsDefault: OptScaCatpcaObjectPlotsType = {
    ObjectPoints: false,
    Biplot: false,
    BiLoadings: false,
    BiCentroids: false,
    Triplot: false,
    BTIncludeAllVars: false,
    BTIncludeSelectedVars: false,
    BTAvailableVars: null,
    BTSelectedVars: null,
    LabelObjLabelByCaseNumber: false,
    LabelObjLabelByVar: false,
    LabelObjAvailableVars: null,
    LabelObjSelectedVars: null,
};

export const OptScaCatpcaCategoryPlotsDefault: OptScaCatpcaCategoryPlotsType = {
    SourceVar: null,
    CatPlotsVar: null,
    JointCatPlotsVar: null,
    TransPlotsVar: null,
    DimensionsForMultiNom: null,
    InclResidPlots: false,
    PrjCentroidsOfVar: null,
    PrjCentroidsOntoVar: null,
};

export const OptScaCatpcaLoadingPlotsDefault: OptScaCatpcaLoadingPlotsType = {
    Variance: false,
    DisplayCompLoadings: false,
    LoadingIncludeAllVars: false,
    LoadingIncludeSelectedVars: false,
    LoadingAvailableVars: null,
    LoadingSelectedVars: null,
    IncludeCentroids: false,
    IncludeCentroidsIncludeAllVars: false,
    IncludeCentroidsIncludeSelectedVars: false,
    IncludeCentroidsAvailableVars: null,
    IncludeCentroidsSelectedVars: null,
};

export const OptScaCatpcaDefault: OptScaCatpcaType = {
    main: OptScaCatpcaMainDefault,
    defineRangeScale: OptScaCatpcaDefineRangeScaleDefault,
    defineScale: OptScaCatpcaDefineScaleDefault,
    discretize: OptScaCatpcaDiscretizeDefault,
    missing: OptScaCatpcaMissingDefault,
    options: OptScaCatpcaOptionsDefault,
    output: OptScaCatpcaOutputDefault,
    save: OptScaCatpcaSaveDefault,
    bootstrap: OptScaCatpcaBootstrapDefault,
    objectPlots: OptScaCatpcaObjectPlotsDefault,
    categoryPlots: OptScaCatpcaCategoryPlotsDefault,
    loadingPlots: OptScaCatpcaLoadingPlotsDefault,
};
