// app/layout.tsx
import type { Metadata } from 'next';
import './globals.css';
import Header from '../components/Layout/Main/Header';
import Footer from '../components/Layout/Main/Footer';
import { ThemeProvider } from "@/components/theme-provider"
import React from "react";

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

import { ModalProvider } from "@/contexts/ModalContext";

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body className={`flex flex-col min-h-screen`}>
        <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
        >
            <ModalProvider>
        <header className="sticky top-0 z-50">
            <Header />
        </header>

        <main className="flex-grow flex">
            <div className="w-full flex flex-col">
                {children}
            </div>
        </main>

        <Footer />
            </ModalProvider>
        </ThemeProvider>
        </body>
        </html>
    );
}
