// app/layout.tsx
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '../components/Layout/Main/Header';
import Footer from '../components/Layout/Main/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body className={`${inter.className} flex flex-col min-h-screen`}>
        <header className="sticky top-0 z-50">
            <Header />
        </header>

        <main className="flex-grow flex">
            <div className="w-full flex flex-col">
                {children}
            </div>
        </main>

        <Footer />
        </body>
        </html>
    );
}
