// app/(dashboard)/layout.tsx
import type { Metadata } from "next";
import "@/app/globals.css";
import Header from "@/components/Header/Dashboard/Header";
import Footer from "@/components/Footer/Dashboard/Footer";
import { ThemeProvider } from "@/components/theme-provider";
import React from "react";
import ModalContainer from "@/components/Modals/ModalContainer";
import DataLoader from "@/components/DataLoader";
import LoadingOverlay from "@/components/LoadingOverlay";

export const metadata: Metadata = {
  title: "Statify",
  description: "Generated by create next app",
};

export default function DashboardLayout({
                                          children,
                                        }: {
  children: React.ReactNode;
}) {
  return (
      <ThemeProvider
          attribute="class"
          defaultTheme=""
          enableSystem
          disableTransitionOnChange
      >
        <DataLoader />

        <div className="h-full w-full m-0 p-0 grid grid-rows-[auto_1fr_auto] overflow-hidden overflow-y-auto">
          <header className="z-50">
            <Header />
          </header>
          <main className="overflow-y-auto">
            <div className="h-full w-full">
              <LoadingOverlay>
                {children}
              </LoadingOverlay>
              <ModalContainer />
            </div>
          </main>
          <footer>
            <Footer />
          </footer>
        </div>
      </ThemeProvider>
  );
}